### ISSUE TITLE
 PA Review: User Authentication

### ISSUE THREAD

**Issue by mattieholtzer** [mattieholtzer/tchat#3]
- [x]  Backend: DB, model, controller, views
- [x]  Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
- [x]  Styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by anastassia-b** [comment]
Functionality is great! I can log in and out, and create a new account. I like that I'm taken to my profile page. To enter my information, I have to "edit" the page, correct? There wont be a form prompting me when I create a new account to fill in those values prior to taking me to my profile?

- [ ] When creating a new account, there is an error if selecting `Bay Area`. It doesn't seem to be a valid option, I get the error `City can't be blank`.

**Comment by anastassia-b** [comment]
Great work! All bugs are now fixed. This MVP is complete.
