### ISSUE TITLE
PA Review: Profile View

### ISSUE THREAD

**Issue by mattieholtzer** [mattieholtzer/tchat#4]
- [x] Users will be able to upload an image along with basic info including pronouns and a bio
- [x] Users will be able to look at their own profile along with an edit option
- [x] Users should be able to access others profiles but can't edit them
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by anastassia-b** [comment]
Great work! To enter my information, I have to always "edit" the page, correct? There wont be a form when I create a new account prompting me to fill in those values prior to taking me to my profile?

**Comment by mattieholtzer** [comment]
Yes that was per intention I wanted users to be able to create accounts fairly quickly and only require the absolute essentials and update their accounts on their own accord.

**Comment by anastassia-b** [comment]
Gotcha! This MVP is complete.
