### ISSUE TITLE
PA Review: Browse Users

### ISSUE THREAD

**Issue by mattieholtzer** [mattieholtzer/tchat#5]
- [x] Users will be able to set and change a location on join and account edit
- [x] Users will be able to access an index page with other users that are in their city, randomly sorted
- [x] Users will be able to go through the index page and access other users accounts through there
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by anastassia-b** [comment]
Nice! I like that it filters the users by city already. Assign me when this is fully ready for review.

**Comment by anastassia-b** [comment]
The `Browse Users` feature correctly filters by the city I am currently in. This MVP is complete!
